server:
  port: 0  # The port on which the service will run

eureka:
  client:
    eureka-server-port: 8761
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/  # URL of the Eureka server
    registerWithEureka: true  # Enable registration with Eureka
    fetchRegistry: true  # Enable fetching the registry from Eureka
  instance:
    hostname: localhost
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}  # Unique ID for the instance
    preferIpAddress: true  # Use IP address instead of hostname

spring:
  application:
    name: catalog-service # Name of the application, used in Eureka

logging:
  level:
    com.netflix.eureka: INFO  # Logging level for Eureka
    org.springframework: INFO  # Logging level for Spring Framework
    root: INFO  # Default logging level

management:
  endpoints:
    web:
      exposure:
        include: info